name: Build Development Installer 8
on: 
  repository_dispatch:
    types: build-development-installer-8
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get the default branch
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      env:
        Default_Branch: ${GITHUB_REF#refs/heads/}
        shell: bash
      
    - name: SET CURRENT_BRANCH
      run: |
        $branchName = "${{github.ref}}".Split("/")["${{github.ref}}".Split("/").Length -1]
        echo "::set-env name=CURRENT_BRANCH::$(echo $branchName)"
      
    - name: Print the default branch
      run: |        
        write-host ${{ env.Default_Branch }}     
      shell: pwsh
