name: Build Development Installer 8
on: 
  repository_dispatch:
    types: build-development-installer-8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get the default branch
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
      
     - name: Print the default branch
      run: |
          write-host ${{ steps.extract_branch.outputs.branch }}
      shell: pwsh
