name: Build Development Installer 8
on: 
  repository_dispatch:
    types: build-development-installer-8
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Extract branch name
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo ${GITHUB_REF#refs/heads/}
      id: extract_branch
       
    - name: Print Release Drafter Config File Name 
      run: |
          write-host ${{ steps.extract_branch.outputs.branch }}
      shell: pwsh
