name: nightly
on: 
  schedule:
  - cron: 45 04 * * *

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        branch: [master,develop,develop8.1]
        
    runs-on: ubuntu-latest
    steps:
    - name: checkout the branch
      uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
    - run: echo checked out the ${{matrix.branch}} branch
    
    - name: Upload TOMEs xUnit artifacts
      uses: actions/upload-artifact@v2      
      with:
        name: TOMEsXUnitTestsResult (${{ matrix.branch }})
        path: .\
      
    

  
